/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author nataly
 */
public class EditarCliente extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    public EditarCliente() {
        initComponents();
    }

    public void nuevaVentana(){
    lblVerficarDatos.setText("");
    txtEditarDircc.setText("");
     txtEditarID.setText("");
    txtEditarNombre.setText("");
    txtEditarTele.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTelefonoClien = new javax.swing.JLabel();
        lblCedulaClien = new javax.swing.JLabel();
        txtEditarID = new javax.swing.JTextField();
        txtEditarDircc = new javax.swing.JTextField();
        txtEditarTele = new javax.swing.JTextField();
        lblDireccionCli = new javax.swing.JLabel();
        lblVerficarDatos = new javax.swing.JLabel();
        btnEditarClien = new javax.swing.JButton();
        btnSalirEditar = new javax.swing.JButton();
        lblTituloConsultarCli = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        txtEditarNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTelefonoClien.setText("Telefono");

        lblCedulaClien.setText("NiT/CC");

        txtEditarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarIDActionPerformed(evt);
            }
        });

        lblDireccionCli.setText("Direccion");

        lblVerficarDatos.setText(" ");

        btnEditarClien.setText("Guardar");
        btnEditarClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienActionPerformed(evt);
            }
        });

        btnSalirEditar.setText("Salir");

        lblTituloConsultarCli.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTituloConsultarCli.setText("Editar Cliente");

        lblNombreCliente.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefonoClien, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDireccionCli, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditarTele)
                            .addComponent(txtEditarDircc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarClien)
                        .addGap(48, 48, 48)
                        .addComponent(btnSalirEditar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(lblTituloConsultarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCedulaClien, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEditarNombre)
                                    .addComponent(txtEditarID, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVerficarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloConsultarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaClien, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtEditarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoClien)
                    .addComponent(txtEditarTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionCli)
                    .addComponent(txtEditarDircc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblVerficarDatos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarClien)
                    .addComponent(btnSalirEditar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarIDActionPerformed

    private void btnEditarClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarClienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarClien;
    private javax.swing.JButton btnSalirEditar;
    private javax.swing.JLabel lblCedulaClien;
    private javax.swing.JLabel lblDireccionCli;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTelefonoClien;
    private javax.swing.JLabel lblTituloConsultarCli;
    private javax.swing.JLabel lblVerficarDatos;
    private javax.swing.JTextField txtEditarDircc;
    private javax.swing.JTextField txtEditarID;
    private javax.swing.JTextField txtEditarNombre;
    private javax.swing.JTextField txtEditarTele;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnEditarClien() {
        return btnEditarClien;
    }

    public void setBtnEditarClien(JButton btnEditarClien) {
        this.btnEditarClien = btnEditarClien;
    }

    public JButton getBtnSalirEditar() {
        return btnSalirEditar;
    }

    public void setBtnSalirEditar(JButton btnSalirEditar) {
        this.btnSalirEditar = btnSalirEditar;
    }

    public JLabel getLblVerficarDatos() {
        return lblVerficarDatos;
    }

    public void setLblVerficarDatos(JLabel lblVerficarDatos) {
        this.lblVerficarDatos = lblVerficarDatos;
    }

    public JTextField getTxtEditarDircc() {
        return txtEditarDircc;
    }

    public void setTxtEditarDircc(JTextField txtEditarDircc) {
        this.txtEditarDircc = txtEditarDircc;
    }

    public JTextField getTxtEditarID() {
        return txtEditarID;
    }

    public void setTxtEditarID(JTextField txtEditarID) {
        this.txtEditarID = txtEditarID;
    }

    public JTextField getTxtEditarTele() {
        return txtEditarTele;
    }

    public void setTxtEditarTele(JTextField txtEditarTele) {
        this.txtEditarTele = txtEditarTele;
    }

    public JTextField getTxtEditarNombre() {
        return txtEditarNombre;
    }

    public void setTxtEditarNombre(JTextField txtEditarNombre) {
        this.txtEditarNombre = txtEditarNombre;
    }



}
