/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Inventario;

/**
 *
 * @author nataly
 */
public class ListaProductos extends javax.swing.JInternalFrame {

    DefaultTableModel dtmProductos = new DefaultTableModel();
    public ArrayList<Inventario> inv = new ArrayList<>();
    
    
    public ListaProductos() {
        initComponents();
        setModelo();
    }

    private void setModelo() {
        String[] cabecera = {"Codigo","Descripción", "Valor und","Stock"};
        dtmProductos.setColumnIdentifiers(cabecera);
        tblProductos.setModel(dtmProductos);

    }
    
     public void setDatos() {
        Object[] datos = new Object[dtmProductos.getColumnCount()];
         dtmProductos.setRowCount(0);
        for (Inventario inventario : inv) {
            datos[0] = inventario.getCodigoBarra();
            datos[1] = inventario.getNombreProducto();
            datos[2] = inventario.getPrecio();
            datos[3] = inventario.getCantidad();
            dtmProductos.addRow(datos);
        }
        tblProductos.setModel(dtmProductos);
    }
     
     public void buscarProductos (String [] arrProd) throws NumberFormatException{
          dtmProductos.setRowCount(0);
         inv = new ArrayList<>();
         boolean  bandera=true;
         for (String arrProd1 : arrProd) {
                String[] textosplit = arrProd1.split(",");
            if (textosplit[1].contains(this.txtNombrePro.getText().toLowerCase())) {
                    String producto = textosplit[1];
                    String valUnit = textosplit[3];
                    String Cant = textosplit[2];
                    String codigo = textosplit[0];
                    bandera=false;
              Inventario Inven = new Inventario(producto, Integer.parseInt(Cant), Long.parseLong(valUnit),Long.parseLong(codigo));
               inv.add(Inven);
                
                }
          } if (bandera) {
             lblVerificarProdu.setText("Producto no encontrado");
         }
     }
     
     public void buscarTodo(String [] arrProd){
         dtmProductos.setRowCount(0);
         inv = new ArrayList<>();
         for (String arrProd1 : arrProd) {
                String[] textosplit = arrProd1.split(",");
                    String producto = textosplit[1];
                    String valUnit = textosplit[3];
                    String Cant = textosplit[2];
                    String codigo = textosplit[0];
            Inventario Inven = new Inventario(producto, Integer.parseInt(Cant), Long.parseLong(valUnit),Long.parseLong(codigo));
            inv.add(Inven);
                
          }
     }
     
     public void nuevaVentana(){
        txtNombrePro.setText("");
        dtmProductos.setRowCount(0);
         inv = new ArrayList<>();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        txtNombrePro = new javax.swing.JTextField();
        btnBuscarProd = new javax.swing.JButton();
        btnTodosProd = new javax.swing.JButton();
        btnSalirListaProd = new javax.swing.JButton();
        lblVerificarProdu = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Productos Registrados ");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductos.getTableHeader().setReorderingAllowed(false);
        tblProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblProductosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        lblNombre.setText("Nombre");

        btnBuscarProd.setText("Buscar");

        btnTodosProd.setText("Mostrar Todo ");

        btnSalirListaProd.setText("Salir");

        lblVerificarProdu.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVerificarProdu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombrePro, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTodosProd)
                            .addComponent(btnBuscarProd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalirListaProd)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodosProd)
                    .addComponent(lblVerificarProdu))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalirListaProd)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProductosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductosKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnSalirListaProd;
    private javax.swing.JButton btnTodosProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblVerificarProdu;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombrePro;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBuscarProd() {
        return btnBuscarProd;
    }

    public void setBtnBuscarProd(JButton btnBuscarProd) {
        this.btnBuscarProd = btnBuscarProd;
    }

    public JButton getBtnSalirListaProd() {
        return btnSalirListaProd;
    }

    public void setBtnSalirListaProd(JButton btnSalirListaProd) {
        this.btnSalirListaProd = btnSalirListaProd;
    }

    public JButton getBtnTodosProd() {
        return btnTodosProd;
    }

    public void setBtnTodosProd(JButton btnTodosProd) {
        this.btnTodosProd = btnTodosProd;
    }

    public JTextField getTxtNombrePro() {
        return txtNombrePro;
    }

    public void setTxtNombrePro(JTextField txtNombrePro) {
        this.txtNombrePro = txtNombrePro;
    }

    public DefaultTableModel getDtmProductos() {
        return dtmProductos;
    }

    public void setDtmProductos(DefaultTableModel dtmProductos) {
        this.dtmProductos = dtmProductos;
    }

    public JTable getTblProductos() {
        return tblProductos;
    }

    public void setTblProductos(JTable tblProductos) {
        this.tblProductos = tblProductos;
    }

    public JLabel getLblVerificarProdu() {
        return lblVerificarProdu;
    }

    public void setLblVerificarProdu(JLabel lblVerificarProdu) {
        this.lblVerificarProdu = lblVerificarProdu;
    }
    
    



}
