
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author harri_8s8jd2i
 */
public class MenuVendedor extends javax.swing.JFrame {

    /**
     * Creates new form MenuVendedor
     */
    public MenuVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        menuItemRegClien = new javax.swing.JMenuItem();
        menuItemConsultarCliente = new javax.swing.JMenuItem();
        menuFactura = new javax.swing.JMenu();
        menuItemCreaFac = new javax.swing.JMenuItem();
        menuCrear = new javax.swing.JMenu();
        menuItemConsultaProd = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        menuCliente.setText("Clientes");

        menuItemRegClien.setText("Registrar cliente");
        menuCliente.add(menuItemRegClien);

        menuItemConsultarCliente.setText("Consultar Cliente");
        menuCliente.add(menuItemConsultarCliente);

        jMenuBar1.add(menuCliente);

        menuFactura.setText("Facturar");

        menuItemCreaFac.setText("Crear factura/Cotización");
        menuFactura.add(menuItemCreaFac);

        jMenuBar1.add(menuFactura);

        menuCrear.setText("Procuctos");

        menuItemConsultaProd.setText("consultar producto");
        menuCrear.add(menuItemConsultaProd);

        jMenuBar1.add(menuCrear);

        menuSalir.setText("Salir");

        menuItemSalir.setText("Salir");
        menuSalir.add(menuItemSalir);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuCrear;
    private javax.swing.JMenu menuFactura;
    private javax.swing.JMenuItem menuItemConsultaProd;
    private javax.swing.JMenuItem menuItemConsultarCliente;
    private javax.swing.JMenuItem menuItemCreaFac;
    private javax.swing.JMenuItem menuItemRegClien;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMenuItemCreaFac() {
        return menuItemCreaFac;
    }

    public void setMenuItemCreaFac(JMenuItem menuItemCreaFac) {
        this.menuItemCreaFac = menuItemCreaFac;
    }

    public JMenuItem getMenuItemConsultaProd() {
        return menuItemConsultaProd;
    }

    public void setMenuItemConsultaProd(JMenuItem menuItemConsultaProd) {
        this.menuItemConsultaProd = menuItemConsultaProd;
    }


    public JMenuItem getMenuItemRegClien() {
        return menuItemRegClien;
    }

    public void setMenuItemRegClien(JMenuItem menuItemRegClien) {
        this.menuItemRegClien = menuItemRegClien;
    }

    

    public JMenuItem getMenuItemSalir() {
        return menuItemSalir;
    }

    public void setMenuItemSalir(JMenuItem menuItemSalir) {
        this.menuItemSalir = menuItemSalir;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JMenuItem getMenuItemConsultarCliente() {
        return menuItemConsultarCliente;
    }

    public void setMenuItemConsultarCliente(JMenuItem menuItemConsultarCliente) {
        this.menuItemConsultarCliente = menuItemConsultarCliente;
    }

   



}
