/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author nataly
 */
public class ConsultarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultarcliente
     */
    public ConsultarCliente() {
        initComponents();
    }

    public void nuevaVentana(){
      lblImprimeID.setText("");
     lblImprimirDirec.setText("");
   lblImprimirNombre.setText("");
    lblImprimirTele.setText("");
    lblVerficarDatos.setText("");
   txtIngresarID.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalirConsul = new javax.swing.JButton();
        lblImprimirTele = new javax.swing.JLabel();
        lblTelefonoClien = new javax.swing.JLabel();
        lblCedulaClien = new javax.swing.JLabel();
        lblImprimirDirec = new javax.swing.JLabel();
        lblImprimeID = new javax.swing.JLabel();
        lblDireccionCli = new javax.swing.JLabel();
        txtIngresarID = new javax.swing.JTextField();
        lblVerficarDatos = new javax.swing.JLabel();
        btnEditarClien = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();
        lblTituloConsultarCli = new javax.swing.JLabel();
        lblInstruccionConsulta = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblImprimirNombre = new javax.swing.JLabel();

        btnSalirConsul.setText("Salir");

        lblImprimirTele.setText(" ");

        lblTelefonoClien.setText("Teléfono");

        lblCedulaClien.setText("NiT/CC");

        lblImprimirDirec.setText(" ");

        lblImprimeID.setText(" ");

        lblDireccionCli.setText("Dirección");

        lblVerficarDatos.setText(" ");

        btnEditarClien.setText("Editar");
        btnEditarClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienActionPerformed(evt);
            }
        });

        btnConsultarCliente.setText("Consultar");

        lblTituloConsultarCli.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTituloConsultarCli.setText("Consultar Cliente");

        lblInstruccionConsulta.setText("Ingrese el ID");

        lblNombreCliente.setText("Nombre");

        lblImprimirNombre.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEditarClien)
                                .addGap(31, 31, 31)
                                .addComponent(btnSalirConsul))
                            .addComponent(lblVerficarDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTituloConsultarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInstruccionConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefonoClien, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDireccionCli, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImprimirDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblImprimirTele, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCedulaClien, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblImprimeID, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombreCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblImprimirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIngresarID, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnConsultarCliente)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloConsultarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruccionConsulta)
                    .addComponent(txtIngresarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaClien, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImprimeID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(lblImprimirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefonoClien)
                    .addComponent(lblImprimirTele, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionCli)
                    .addComponent(lblImprimirDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVerficarDatos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarClien)
                    .addComponent(btnSalirConsul))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarClienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnEditarClien;
    private javax.swing.JButton btnSalirConsul;
    private javax.swing.JLabel lblCedulaClien;
    private javax.swing.JLabel lblDireccionCli;
    private javax.swing.JLabel lblImprimeID;
    private javax.swing.JLabel lblImprimirDirec;
    private javax.swing.JLabel lblImprimirNombre;
    private javax.swing.JLabel lblImprimirTele;
    private javax.swing.JLabel lblInstruccionConsulta;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTelefonoClien;
    private javax.swing.JLabel lblTituloConsultarCli;
    private javax.swing.JLabel lblVerficarDatos;
    private javax.swing.JTextField txtIngresarID;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnConsultarCliente() {
        return btnConsultarCliente;
    }

    public void setBtnConsultarCliente(JButton btnConsultarCliente) {
        this.btnConsultarCliente = btnConsultarCliente;
    }

    public JButton getBtnEditarClien() {
        return btnEditarClien;
    }

    public void setBtnEditarClien(JButton btnEdiarClien) {
        this.btnEditarClien = btnEdiarClien;
    }

    public JButton getBtnSalirClien() {
        return btnSalirConsul;
    }

    public void setBtnSalirClien(JButton btnSalirClien) {
        this.btnSalirConsul = btnSalirClien;
    }

    public JLabel getLblVerficarDatos() {
        return lblVerficarDatos;
    }

    public void setLblVerficarDatos(JLabel lblVerficarDatos) {
        this.lblVerficarDatos = lblVerficarDatos;
    }

    public JButton getBtnSalirConsul() {
        return btnSalirConsul;
    }

    public void setBtnSalirConsul(JButton btnSalirConsul) {
        this.btnSalirConsul = btnSalirConsul;
    }

    public JLabel getLblImprimeID() {
        return lblImprimeID;
    }

    public void setLblImprimeID(JLabel lblImprimeID) {
        this.lblImprimeID = lblImprimeID;
    }

    public JLabel getLblImprimirDirec() {
        return lblImprimirDirec;
    }

    public void setLblImprimirDirec(JLabel lblImprimirDirec) {
        this.lblImprimirDirec = lblImprimirDirec;
    }

    public JLabel getLblImprimirTele() {
        return lblImprimirTele;
    }

    public void setLblImprimirTele(JLabel lblImprimirTele) {
        this.lblImprimirTele = lblImprimirTele;
    }

    public JTextField getTxtIngresarID() {
        return txtIngresarID;
    }

    public void setTxtIngresarID(JTextField txtIngresarID) {
        this.txtIngresarID = txtIngresarID;
    }

    public JLabel getLblImprimirNombre() {
        return lblImprimirNombre;
    }

    public void setLblImprimirNombre(JLabel lblImprimirNombre) {
        this.lblImprimirNombre = lblImprimirNombre;
    }

    


}
