/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author harri_8s8jd2i
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escrito = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        menuItemRegProd = new javax.swing.JMenuItem();
        menuItemRegEmpl = new javax.swing.JMenuItem();
        menuItemRegClien = new javax.swing.JMenuItem();
        menuModificar = new javax.swing.JMenu();
        menuItemModClien = new javax.swing.JMenuItem();
        menuItemConsInventario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemGenCot = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritoLayout = new javax.swing.GroupLayout(escrito);
        escrito.setLayout(escritoLayout);
        escritoLayout.setHorizontalGroup(
            escritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1009, Short.MAX_VALUE)
        );
        escritoLayout.setVerticalGroup(
            escritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        menuRegistrar.setText("Registrar");

        menuItemRegProd.setText("Registrar producto");
        menuRegistrar.add(menuItemRegProd);

        menuItemRegEmpl.setText("Registrar empleado");
        menuItemRegEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegEmplActionPerformed(evt);
            }
        });
        menuRegistrar.add(menuItemRegEmpl);

        menuItemRegClien.setText("Registrar cliente");
        menuRegistrar.add(menuItemRegClien);

        jMenuBar1.add(menuRegistrar);

        menuModificar.setText("Consultar");

        menuItemModClien.setText("Consultar cliente");
        menuModificar.add(menuItemModClien);

        menuItemConsInventario.setText("Consultar Inventario");
        menuItemConsInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsInventarioActionPerformed(evt);
            }
        });
        menuModificar.add(menuItemConsInventario);

        jMenuBar1.add(menuModificar);

        jMenu3.setText("Generar");

        menuItemGenCot.setText("Generar cotizacion/Factura");
        jMenu3.add(menuItemGenCot);

        jMenuBar1.add(jMenu3);

        menuSalir.setText("Salir");

        menuItemSalir.setText("Salir");
        menuSalir.add(menuItemSalir);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRegEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegEmplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemRegEmplActionPerformed

    private void menuItemConsInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemConsInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escrito;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemConsInventario;
    private javax.swing.JMenuItem menuItemGenCot;
    private javax.swing.JMenuItem menuItemModClien;
    private javax.swing.JMenuItem menuItemRegClien;
    private javax.swing.JMenuItem menuItemRegEmpl;
    private javax.swing.JMenuItem menuItemRegProd;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuModificar;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables

    
    public JMenuItem getMenuItemGenCot() {
        return menuItemGenCot;
    }

    public void setMenuItemGenCot(JMenuItem menuItemGenCot) {
        this.menuItemGenCot = menuItemGenCot;
    }


    public JMenuItem getMenuItemModClien() {
        return menuItemModClien;
    }

    public void setMenuItemModClien(JMenuItem menuItemModClien) {
        this.menuItemModClien = menuItemModClien;
    }

    public JMenuItem getMenuItemRegClien() {
        return menuItemRegClien;
    }

    public void setMenuItemRegClien(JMenuItem menuItemRegClien) {
        this.menuItemRegClien = menuItemRegClien;
    }

    public JMenuItem getMenuItemRegEmpl() {
        return menuItemRegEmpl;
    }

    public void setMenuItemRegEmpl(JMenuItem menuItemRegEmpl) {
        this.menuItemRegEmpl = menuItemRegEmpl;
    }

    public JMenu getMenuModificar() {
        return menuModificar;
    }

    public void setMenuModificar(JMenu menuModificar) {
        this.menuModificar = menuModificar;
    }

    public JMenu getMenuRegistrar() {
        return menuRegistrar;
    }

    public void setMenuRegistrar(JMenu menuRegistrar) {
        this.menuRegistrar = menuRegistrar;
    }

    public JMenu getMenuSalir() {
        return menuSalir;
    }

    public void setMenuSalir(JMenu menuSalir) {
        this.menuSalir = menuSalir;
    }

    public JPanel getEscrito() {
        return escrito;
    }

    public void setEscrito(JPanel escrito) {
        this.escrito = escrito;
    }

    public JMenuItem getMenuItemSalir() {
        return menuItemSalir;
    }

    public void setMenuItemSalir(JMenuItem menuItemSalir) {
        this.menuItemSalir = menuItemSalir;
    }



    public JMenuItem getMenuItemRegProd() {
        return menuItemRegProd;
    }

    public void setMenuItemRegProd(JMenuItem menuItemRegProd) {
        this.menuItemRegProd = menuItemRegProd;
    }

    public JMenuItem getMenuItemConsInventario() {
        return menuItemConsInventario;
    }

    public void setMenuItemConsInventario(JMenuItem menuItemConsInventario) {
        this.menuItemConsInventario = menuItemConsInventario;
    }

    





}
